---
nginx_http_params:
  # bennojoy.nginx does not correctly replace these log directives
  #access_log: /var/log/nginx/access.log
  #error_log: /var/log/nginx/error.log                                    
  sendfile: "on"                                      
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: "65"

nginx_sites:
  - server:
      file_name: default
      listen: 80
      server_name: localhost
      root: /usr/share/nginx/html
      index: index.html
      location1:
        name: /
        try_files: "$uri $uri/ /index.html"

  # Redirect www.app.dev to app.dev
  - server:
      file_name: www.app
      listen: 80
      server_name: www.app.dev
      rewrite: "^ http://app.dev$uri permanent"
