---
- name: Install Essential Packages
  package: pkg={{ item }} state=present
  with_items:
    - curl
    - python-pycurl

- name: Install Git
  package: pkg=git-core state=present

- name: Install Headless GUI emulators (Xvfb, matchbox-window-manager)
  package: pkg={{ item }} state=present
  with_items:
    - xvfb
    - matchbox-window-manager
